[package]
name = "luau_behavior"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
mlua = { version = "0.9", features = ["luau"] }
notify = "6"
bevy_app = { path = "../../crates/bevy_app", version = "0.16.0-dev" }
bevy_ecs = { path = "../../crates/bevy_ecs", version = "0.16.0-dev" }
bevy_input = { path = "../../crates/bevy_input", version = "0.16.0-dev" }
bevy_time = { path = "../../crates/bevy_time", version = "0.16.0-dev" }
bevy_utils = { path = "../../crates/bevy_utils", version = "0.16.0-dev" }
luau_behavior_macros = { path = "macros" }
crossbeam-channel = "0.5"

[features]
default = ["std"]
std = []

[lints]
workspace = true
