[package]
name = "simulatedentity"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy_app = { path = "../../crates/bevy_app", version = "0.16.0-dev" }
bevy_ecs = { path = "../../crates/bevy_ecs", version = "0.16.0-dev" }
bevy_math = { path = "../../crates/bevy_math", version = "0.16.0-dev" }
bevy_time = { path = "../../crates/bevy_time", version = "0.16.0-dev" }
simulatedentity_macro = { path = "../simulatedentity_macro" }
memoffset = "0.9"

[features]
default = []

[lints]
workspace = true
